### ISSUE TITLE
Archive `odimh5` repository

### ISSUE THREAD

**Issue by peterdesmet** [enram/vptstools#15]
- [x] @stijnvanhoey Verify `odimh5` functionality is integrated in vptstools 
- [ ] @stijnvanhoey Can `odimh5` be removed from PyPI? See also https://github.com/enram/odimh5/issues/2. Or be marked as deprecated?
- [x] @peterdesmet archive repository: https://github.com/enram/odimh5

**Comment by stijnvanhoey** [comment]
I propose to mark odim5 as a deprecated package in pypi with a 

 ```
from setuptools import setup
setup(name = "odim5",
      version="1.0.0",
      install_requires=["vptstools"],
)
 ```

**Comment by peterdesmet** [comment]
The repo https://github.com/enram/odimh5 is now archived.

@niconoe can you update the odim5 pypi page as suggested by @stijnvanhoey above? We don't have write access.

**Comment by niconoe** [comment]
Hello,

I updated the package as suggested by @stijnvanhoey and pushed it to PyPI, I didn't knew this approach but it indeed looks like the right thing to do. 

I wanted to try that the redirect works from a user perspective (asking to install odimh5 in a fresh virtualenv), but I couldn't make it work since it appears vptstools is currently unavailaible on PyPI, see https://pypi.org/search/?q=vptstools

The behavior we currently observe is:

1) Fail if we request the "new version":

```
pip install odimh5==1.0.0                                           ✔  odimh5-test-redirect-2 3.10.5   10:43:03 
Collecting odimh5==1.0.0
  Using cached odimh5-1.0.0-py3-none-any.whl (3.2 kB)
ERROR: Could not find a version that satisfies the requirement vptstools (from odimh5) (from versions: none)
ERROR: No matching distribution found for vptstools
```

2) fallback to the old version if no specific version required:

```
pip install odimh5                                                    ✔  odimh5-test-redirect 3.10.5   10:41:24 
Collecting odimh5
  Downloading odimh5-1.0.0-py3-none-any.whl (3.2 kB)
  Using cached odimh5-0.1.0-py3-none-any.whl (3.9 kB)
Collecting h5py>=3.1.0
  Using cached h5py-3.8.0-cp310-cp310-macosx_11_0_arm64.whl (2.6 MB)
Collecting pytz
  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
Collecting numpy>=1.14.5
  Using cached numpy-1.24.3-cp310-cp310-macosx_11_0_arm64.whl (13.9 MB)
Installing collected packages: pytz, numpy, h5py, odimh5
Successfully installed h5py-3.8.0 numpy-1.24.3 odimh5-0.1.0 pytz-2023.3
```

**I suggest that we retry those 2 cases after vptstools is available and make sure the redirect works as expected.**

Please note that I didn't pushed the "redirect change" to GitHub, since the repository is now read-only.

**Comment by peterdesmet** [comment]
@niconoe if you want I can temporarily unarchive the repo for you.

**Comment by niconoe** [comment]
We can do that!

**Comment by peterdesmet** [comment]
@niconoe now unarchived, let me know when I can archive it again.

**Comment by niconoe** [comment]
You can now!

**Comment by peterdesmet** [comment]
Done
