### ISSUE TITLE
Sample data for unit testing

### ISSUE THREAD

**Issue by stijnvanhoey** [enram/vptstools#5]
@niconoe when running the current unit tests, there is a reference to sample data, which is not available in the repository. Is there a reference or documentation available on the example data setup? Should I just put 'any' h5 file to make the `test_error_non_vp_source_file` test working (as this should fail)?

**Comment by niconoe** [comment]
Wow, good catch. I guess I forgot to push the sample data directory, and now it's gone (work computer back to IT ops and formatted).

Since the tests are really, really basic for now, I suggest to recreate a sample data directory and populate it with suitable files so the tests pass.

Very sorry about that, good luck!

**Comment by stijnvanhoey** [comment]
Nico, thanks for the response. With the current tests, a real file was not yet 'really' required and some dummy data just did the job while doing some refactoring, see https://github.com/enram/vptstools/pull/6/files#diff-7beaa1a99c6946852a54d4b906950a25d1271155839d67e8346563435cd02d37
