### ISSUE TITLE
Documentation build warning

### ISSUE THREAD

**Issue by peterdesmet** [enram/vptstools#57]
When running `tox -e docs`, all works fine, but a warning is raised:

```ini
/Users/peter_desmet/Coding/Repositories/enram/vptstools/src/vptstools/__init__.py:docstring of vptstools.vpts.vpts:1: WARNING: duplicate object description of vptstools.vpts, other instance in api/vptstools, use :no-index: for one of them
WARNING: autodoc: failed to import module 'transfer_baltrad' from module 'vptstools.bin'; the following exception was raised:
cannot import name 'report_exception_to_sns' from 'vptstools.bin.click_exception' (/Users/peter_desmet/Coding/Repositories/enram/vptstools/docs/../src/vptstools/bin/click_exception.py)
```

**Comment by stijnvanhoey** [comment]
My mistake, I did not properly update when combining the different PRs/branches from yesterday. Fixed in a015927.

Note: you can ignore the `/home/stijnvh/Documents/repositories/vptstools/src/vptstools/__init__.py:docstring of vptstools.vpts.vpts:1: WARNING: duplicate object description of vptstools.vpts, other instance in api/vptstools, use :noindex: for one of them` message as things are rendered as expected.
