### ISSUE TITLE
run vptstools via cli

### ISSUE THREAD

**Issue by PietrH** [enram/vptstools#73]
I've installed vptstools via pip:

```
pip install vptstools
pip install vptstools\[transfer\]
```

But can't use the routines on the command line: https://github.com/enram/vptstools/blob/main/docs/click.rst

- transfer_baltrad
- vph5_to_vpts

I just get a command not found, should I have added it to path somehow?

**Comment by PietrH** [comment]
Fixed it, when I installed the pre release I got a warning the two tools were installed in a dir not on my path, I've added the path to bashrc and now it works.

**Comment by stijnvanhoey** [comment]
> I just get a command not found, should I have added it to path somehow?

Adding to the path should not have been required and the CLI commands should be available when the virtual environment (venv or conda) where you installed the package is activated. Can you check that the virtual env was active when you tried the commands? 

The package uses the 'entry-point' concept as described in the setuptools documentaiton, see https://setuptools.pypa.io/en/latest/userguide/entry_point.html

**Comment by stijnvanhoey** [comment]
> The readme used pip, I used pip. Run in a Linux Mint 21 VM. 

I'm trying to troubleshoot the issue as adding elements to path manually is something that should not be required using the entry-point approach. In order to find out the possible causes, I'm wondering if you used a [virtual environment](https://docs.python.org/3/library/venv.html) to install the package with pip? If that would be the reason, we can improve the installation instructions for future users. 

> I believe the readme is broken when it comes to the cli modules anyway:

That is the trade-off we made to have the CLI endpoint information directly loaded from the code documentation (as defined in click) so it keeps up to date in the sphinx documentation, see https://enram.github.io/vptstools/#cli-endpoints instead of keeping documentation updated in two locations.

**Comment by PietrH** [comment]
> I'm wondering if you used a [virtual environment](https://docs.python.org/3/library/venv.html)

I did not. 

> instead of keeping documentation updated in two locations

Fair enough
